export const projects = [
  {
    title: 'Promptopia App',
    description: "Built a Modern UI/UX using Next JS, React JS, TailwindCSS, MongoDB, Mongoose, Google Cloud Api. It encompasses all modern UX Practices, follows a stringent and well-organised File Structure, uses React Functional components to create components, Tailwind for styling, and Next JS for Client/Server side rendering, serverless route handling, metadata, SEO.",
      image: '/images/promptopia.png',
      tags: ['Next', 'React', 'TailwindC', 'Vite', 'Vercel'],
    source: 'https://github.com/CBelloxxi/Promptopia',
    visit: 'https://promptopia-xi-ten.vercel.app/',
    id: 0,
  },
  {
    title: 'HooBank App',
    description: "Built with a Modern UI/UX using Vite, React JS and Tailwind CSS. It encompasses all modern UX Practices, follows a stringent and well-organised File Structure, uses React Functional components to create reusable card components and tailwindcss for all styling, Vite has been used as the bundler for this build. Netlify has also been used for free hosting.",
      image: '/images/hoobank.png',
      tags: ['Javascript', 'React', 'TailwindC', 'Vite', 'Netlify'],
    source: 'https://github.com/CBelloxxi/bank_modern_app',
    visit: 'https://main--jovial-mochi-6f0e1d.netlify.app/',
    id: 0,
  },
  {
    title: 'Gericht Restaurant',
    description:"Built with a Modern UI/UX using React JS. It encompasses all modern UX Practices, follows a stringent and well organised File Structure and uses React Functional components to create a reusable SubHeading component, which has been used multiple times in the project. React Icons Framework has also been used. Netlify has been used for hosting.",
    image: '/images/gericht.png',
    tags: ['JS', 'Create-React-App', 'CSS BEM Model', 'Netlify'],
    source: 'https://github.com/CBelloxxi/gericht-restaurant',
    visit: 'https://mellifluous-axolotl-5edf7d.netlify.app/',
    id: 1,
  },
  {
    title: 'Modern GPT-3',
    description: "Built with a Modern UI/UX using React JS. It encompasses all modern UX Practices, follows a stringent and well organised File Structure and uses React Functional components to recreate multiple components throughout the project. It aims to be in the style of a modern GPT-3 Landing Page if it needed one. Also, Netlify has been used for free hosting.",
      image: '/images/gpt3.png',
      tags: ['JS', 'React', 'React Functional Components', 'Netlify'],
    source: 'https://github.com/CBelloxxi/GPT3-Clone',
    visit: 'https://master--friendly-liger-890838.netlify.app/',
    id: 2,
  },
  {
    title: 'Friendy App',
    description: "Safely donate contactlessly to the homeless utilizing uniquely generated QR codes - Scan their QR Code, have a look at their Profile & Donate! Now you don't have to lie and say you don't carry cash anymore. Rails used to build the framework, JS for the Stripe and Mapbox API, Active Record and MVC for path structure. Unique QR Codes are generated for each individual.",
    image: '/images/friendy.png',
    tags: ['Rails', 'JS', 'HTML', 'SCSS', 'ActiveRecord', 'OOP', 'MVC'],
    source: 'https://github.com/CBelloxxi/Friendy',
    visit: 'https://friendy.io/',
    id: 3,
  },
];

export const TimeLineData = [
  { year: 2019, text: 'Studied & Worked full-time at Barclays. Published Student Researcher in BAME Attainment. Was awarded for Social Initiative & Innovative Ideas.', },
  { year: 2020, text: 'Continued studying & working. Changemaker Ambassador, recognised & represented my Uni as Ambassador for in Social Change.', },
  { year: 2021, text: 'Graduated with 1st Class w/Honours, worked at EmpowerRD as an SDR, from Summer to Winter 2021. Left Job start of 2022.', },
  { year: 2022, text: 'Completed Le Wagon 9-Week Web Dev Bootcamp, continued self-teaching MERN Stack. Created a small start-up called Friendy.', },
  { year: 2023, text: 'Developed multiple ecom sites. Continued Entrepreneur route & Contracted as Junior Frontend Developer @ Journeo.', },
  { year: 2024, text: 'Currently in search of Full Stack or Frontend Developer Role, Studying Harvard CS50 & building lots of Next / React JS projects.', },
];
